# Generated by Django 2.0 on 2018-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='language',
            field=models.IntegerField(choices=[(1, 'русский'), (2, 'қазақша'), (3, 'english')], default=1),
        ),
    ]
