# Generated by Django 2.1 on 2018-08-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='has_jack_of_clubs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
