# Generated by Django 2.0 on 2018-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20180316_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_jack_of_clubs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='trump_is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
