# Generated by Django 2.1 on 2018-08-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_deck_has_jack_of_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='has_jack_of_clubs',
        ),
    ]
