# Generated by Django 2.0 on 2018-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20180316_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='clubs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='diamonds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='hearts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='spades',
            field=models.BooleanField(default=False),
        ),
    ]
