# Generated by Django 2.1 on 2018-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_deck_has_jack_of_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='label',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='current_label',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
