# Generated by Django 2.1 on 2018-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20180828_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='team01_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='team02_received',
            field=models.BooleanField(default=False),
        ),
    ]
