# Generated by Django 2.1 on 2018-08-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20180829_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='previous_eggs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
