# Generated by Django 2.0 on 2018-03-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20180316_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='previous_eggs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='total_team01',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='total_team02',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
