# Generated by Django 2.1 on 2018-08-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20180831_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='previous_eggs',
        ),
    ]
