# Generated by Django 2.1 on 2018-08-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_room_previous_eggs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='previous_eggs',
        ),
    ]
