# Generated by Django 2.0 on 2018-03-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
