# Generated by Django 2.0 on 2018-03-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180308_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='trump',
            field=models.PositiveSmallIntegerField(choices=[(1, 'clubs'), (2, 'spades'), (3, 'hearts'), (4, 'diamonds')], default=(1, 'clubs')),
        ),
    ]
