# Generated by Django 2.0 on 2018-03-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='owner',
        ),
    ]
