# Generated by Django 2.0 on 2018-03-11 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesettings',
            name='owner',
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='ace_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='on_eggs',
            field=models.IntegerField(choices=[(1, 'on_eggs_open_four'), (2, 'on_eggs_open_double')], default=1),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='on_full',
            field=models.IntegerField(choices=[(1, 'open_four'), (2, 'finish_game')], default=1),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='game.Room'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='save',
            field=models.IntegerField(choices=[(30, 'save_30'), (31, 'save_31')], default=30),
        ),
    ]
