# Generated by Django 2.0 on 2018-03-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180311_0740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameSettings',
            new_name='Settings',
        ),
    ]
