# Generated by Django 2.0 on 2018-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20180311_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='save',
        ),
        migrations.AddField(
            model_name='settings',
            name='on_save',
            field=models.IntegerField(choices=[(30, 'on_save_30'), (31, 'on_save_31')], default=30),
        ),
    ]
