# Generated by Django 2.0 on 2018-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20180311_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='on_full',
            field=models.IntegerField(choices=[(1, 'on_full_open_four'), (2, 'on_full_finish_game')], default=1),
        ),
    ]
