# Generated by Django 2.0 on 2018-03-11 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0010_auto_20180311_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='room',
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
