

INITIAL_INDEX = 1
INITIAL_PLAYER_INDEX = 1
TOTAL_MOVES_INITIAL = 0

#   Sums
INITIAL_SUM = 0
SAVE_SUM_30 = 30
SAVE_SUM_31 = 31
FULL_SUM = 120

TEAM_MAX = 12
TEAM_MAX_LOCAL = 120

#   indices of players
FIRST_PLAYER_INDEX = 1
SECOND_PLAYER_INDEX = 2
THIRD_PLAYER_INDEX = 3
FOURTH_PLAYER_INDEX = 4

#   names of players
FIRST_PLAYER_NAME = "FIRST_PLAYER"
SECOND_PLAYER_NAME = "SECOND_PLAYER"
THIRD_PLAYER_NAME = "THIRD_PLAYER"
FOURTH_PLAYER_NAME = "FOURTH_PLAYER"

#   indices of teams
TEAM_ONE = (
    (FIRST_PLAYER_INDEX, FIRST_PLAYER_NAME),
    (THIRD_PLAYER_INDEX, THIRD_PLAYER_NAME),
)
TEAM_TWO = (
    (SECOND_PLAYER_INDEX, SECOND_PLAYER_NAME),
    (FOURTH_PLAYER_INDEX, FOURTH_PLAYER_NAME),
)

#   Names of teams
TEAM_ONE_NAME = "team_01"
TEAM_TWO_NAME = "team_02"

TEAMS = (
    (TEAM_ONE, TEAM_ONE_NAME),
    (TEAM_TWO, TEAM_TWO_NAME),
)

MATCH_NAME = "match"

GAME_NAME = "game"

SEVEN = 7
SEVEN_WORTH = 0
EIGHT = 8
EIGHT_WORTH = 0
NINE = 9
NINE_WORTH = 0
JACK = 10
JACK_WORTH = 2
QUEEN = 11
QUEEN_WORTH = 3
KING = 12
KING_WORTH = 4
TEN = 13
TEN_WORTH = 10
ACE = 14
ACE_WORTH = 11

TRUMP_PRIORITY_SEVEN = 93
TRUMP_PRIORITY_EIGHT = 94
TRUMP_PRIORITY_NINE = 95
TRUMP_PRIORITY_JACK = 100
TRUMP_PRIORITY_QUEEN = 96
TRUMP_PRIORITY_KING = 97
TRUMP_PRIORITY_TEN = 98
TRUMP_PRIORITY_ACE = 99

CARD_NUMBERS = (
    (SEVEN, SEVEN_WORTH, TRUMP_PRIORITY_SEVEN, "7"),
    (EIGHT, EIGHT_WORTH, TRUMP_PRIORITY_EIGHT, "8"),
    (NINE, NINE_WORTH, TRUMP_PRIORITY_NINE, "9"),
    (TEN, TEN_WORTH, TRUMP_PRIORITY_TEN, "10"),
    (JACK, JACK_WORTH, TRUMP_PRIORITY_JACK, "jack"),
    (QUEEN, QUEEN_WORTH, TRUMP_PRIORITY_QUEEN, "queen"),
    (KING, KING_WORTH, TRUMP_PRIORITY_KING, "king"),
    (ACE, ACE_WORTH, TRUMP_PRIORITY_ACE, "ace"),
)

CARD_NAMES = (
    (SEVEN, "7"),
    (EIGHT, "8"),
    (NINE, "9"),
    (TEN, "10"),
    (JACK, "jack"),
    (QUEEN, "queen"),
    (KING, "king"),
    (ACE, "ace"),
)

#   Values of Trumps
CLUBS_VALUE = 1
SPADES_VALUE = 2
HEARTS_VALUE = 3
DIAMONDS_VALUE = 4

#   Names of trumps
CLUBS_NAME = "clubs"
SPADES_NAME = "spades"
HEARTS_NAME = "hearts"
DIAMONDS_NAME = "diamonds"

INITIAL_TRUMP = 1

SUITS = (
    (CLUBS_VALUE, CLUBS_NAME),
    (SPADES_VALUE, SPADES_NAME),
    (HEARTS_VALUE, HEARTS_NAME),
    (DIAMONDS_VALUE, DIAMONDS_NAME),
)

INITIAL_CIRCLE = 1
FINAL_CIRCLE = 8

HAND01 = 1
HAND02 = 2
HAND03 = 3
HAND04 = 4

MOVES_QUEUE = (
    (HAND01, u'hand01'),
    (HAND02, u'hand02'),
    (HAND03, u'hand03'),
    (HAND04, u'hand04'),
)



