# Generated by Django 2.0 on 2018-03-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_save', models.IntegerField(choices=[(30, 'on_save_30'), (31, 'on_save_31')], default=30)),
                ('on_full', models.IntegerField(choices=[(1, 'on_full_open_four'), (2, 'on_full_finish_game')], default=1)),
                ('ace_allowed', models.BooleanField(default=True)),
                ('on_eggs', models.IntegerField(choices=[(1, 'on_eggs_open_four'), (2, 'on_eggs_open_double')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
